### ISSUE TITLE
Warning: Requires main queue setup

### ISSUE THREAD

**Issue by ennaed11** [ErlichChen/react-native-healthkit#1]
Hello I get this warning whenever I run my ios app. I'm not sure what triggers it but I use it together with rn-apple-healthkit. Can this cause problems for my app in the future? Is there a way to fix this? 

![image](https://user-images.githubusercontent.com/37971836/49159830-53044980-f360-11e8-975f-6b283a7b7cb8.png)

**Comment by ErlichChen** [comment]
Hi, Thank you for reporting the issue. 
https://facebook.github.io/react-native/docs/native-modules-ios.html#threading.
I need to implement requiresMainQueueSetup method in the bridge class.
Which version of React native do you use?

**Comment by ennaed11** [comment]
My react-native version is 0.57.0

**Comment by ErlichChen** [comment]
I push some new change.  hope can help you to fix it.

**Comment by ennaed11** [comment]
That removed the warning. Thank you so much!
